server:
  port: 8082

eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductManagement
    username: postgres
    password: 5071
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
      hibernate:
        ddl_auto: update
      show_sql: true